version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
  similar-code:
    config:
      # yamllint disable-line rule:empty-values
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      # yamllint disable-line rule:empty-values
      threshold: # language-specific defaults. an override will affect all languages.
