# FROM golang:buster as app
FROM library/golang:buster as app
RUN mkdir -p /yopass
WORKDIR /yopass
COPY . .
RUN go build ./cmd/yopass && \
    go build ./cmd/yopass-server

# FROM node as website
FROM library/node:18-slim as website
COPY website /website
WORKDIR /website
RUN DEBIAN_FRONTEND=noninteractive \
    cp --force .env.test .env.production && \
    cat --show-all .env && \
    cat --show-all .env.production && \
    yarn install && \
    PUBLIC_URL='https://onetime.test-elvia.io' \
    REACT_APP_BACKEND_URL='https://onetime.test-elvia.io' \
    yarn build

# hadolint ignore=DL3006
FROM gcr.io/distroless/base
COPY --from=app --chown=nonroot:nonroot /yopass/yopass /yopass/yopass-server /
COPY --from=website --chown=nonroot:nonroot /website/build /public
USER nonroot
ENTRYPOINT ["/yopass-server"]
