FROM golang:buster as app
RUN mkdir -p /yopass
WORKDIR /yopass
COPY . .
RUN go build ./cmd/yopass && go build ./cmd/yopass-server

FROM node:16 as website
COPY website /website
WORKDIR /website
RUN yarn install --network-timeout 600000
RUN REACT_APP_DISABLE_FEATURES_CARDS=1 REACT_APP_TITLE="Phocas Encrypt" yarn build

FROM gcr.io/distroless/base
COPY --from=app /yopass/yopass /yopass/yopass-server /
COPY --from=website /website/build /public
ENTRYPOINT ["/yopass-server"]
