apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yopass
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yopass
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: yopass
          image: jhaals/yopass
          args:
            - "--database=mongo"
            - "--mongo=mongodb://localhost:27017"
          ports:
            - name: http
              containerPort: 1337
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
        - name: yopass-mongodb
          image: bitnami/mongodb
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: mongodb
              containerPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: yopass
spec:
  selector:
    app.kubernetes.io/name: yopass
  type: ClusterIP
  ports:
    - name: http
      port: 1337
