version: "3.0"

services:
  mongodb:
    image: bitnami/mongodb
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: secret_root
      MONGODB_DATABASE: yopass
    expose:
      - "27017"

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    command: "--database mongo --mongo=mongodb://root:secret_root@mongodb:27017 --port 8080"
