---
# Source: elvia-deployment/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: yopass
  namespace: onetime
  labels:
    app: yopass
spec:
  ports:
    - name: yopass-port
      port: 1337
    - name: yopass-prometheus-port
      port: 2112
  selector:
    app: yopass
---
# Source: elvia-deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass
  namespace: onetime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yopass
      microservice-type: worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yopass
        microservice-type: worker
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: yopass
      imagePullSecrets:
        - name: "ContainerRegistryElvia"
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        supplementalGroups: [65532]
      containers:
        - name: yopass
          image: containerregistryelvia.azurecr.io/onetime-yopass:image-tag-value
          env:
            - name: VAULT_ADDR
              value: https://elvia-vault-value
            - name: ROLE
              value: yopass
            - name: MOUNT_PATH
              value: kubernetes/runtimeservice/onetime/yopass
            - name: REACT_APP_ELVID_AUTHORITY
              value: https://elvid-authority-value
            - name: REACT_APP_ELVID_CLIENT_ID
              value: elvid-client-id-value
            - name: REACT_APP_ELVID_REDIRECT_URI
              value: https://onetime-url-value/callback
            - name: REACT_APP_ELVID_SCOPE
              value: elvid-scope-value
            - name: ONETIME_ELVID_BASE_URL
              value: https://elvid-authority-value
          args:
            - "--metrics-port=2112"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 100Mi
---
# Source: elvia-deployment/templates/service-monitor.yaml
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: yopass
  namespace: onetime
spec:
  endpoints:
    - port: yopass-prometheus-port
  selector:
    matchLabels:
      app: yopass
---
# Source: elvia-deployment/templates/ingressroute.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: yopass
  namespace: onetime
spec:
  routes:
    - kind: Rule
      match: Host(`onetime-url-value`)
      middlewares:
        - name: hsts-header
          namespace: dns
        - name: remove-metrics
          namespace: dns
      services:
        # Named port is only supported after Traefik >= v2.5.0 versions.
        # See `Add named port support to Kubernetes IngressRoute CRDs.` commit.
        # https://github.com/traefik/traefik/commit/bbee63fcf37c84940c248e5978f79e886698e4b1
        # - port: yopass-port
        - name: yopass
          port: 1337
